# Latest version (23.02.19)
version: "3.8"

# Containers orchestrated by Docker Compose
services:
  # MariaDB
  mariadb:
    # Container name
    container_name: mariadb
    # Dockerfile location
    build: ./requirements/mariadb
    # Image name
    image: ft_mariadb:inception
    # Docker init
    init: true
    # Network
    networks:
      - ft_bridge
    # Bind mount
    volumes:
      - ${VOLUME_PATH}/db_vol:${DB_PATH}
    # Environment variables
    env_file:
      - .env
    # Configuration settings
    configs:
      - source: mariadb_config
        target: /etc/my.cnf
    # Keep the service active
    restart: "always"

  # WordPress
  wordpress:
    # Container name
    container_name: wordpress
    # Dockerfile location
    build: ./requirements/wordpress
    # Image name
    image: ft_wordpress:inception
    # Docker init
    init: true
    # Network
    networks:
      - ft_bridge
    # Bind mount
    volumes:
      - ${VOLUME_PATH}/wp_vol:${WP_PATH}
    # Environment variables
    env_file:
      - .env
    # Configuration settings
    configs:
      - source: wordpress_fpm_config
        target: /etc/php8/php-fpm.d/www.conf
    # Guarantee the sequence
    depends_on:
      mariadb:
        condition: service_healthy
    # Keep the service active
    restart: "always"

  # NginX
  nginx:
    # Container name
    container_name: nginx
    # Dockerfile location
    build: ./requirements/nginx
    # Image name
    image: ft_nginx:inception
    # Docker init
    init: true
    # Network
    networks:
      - ft_bridge
    # Bind mount
    volumes:
      - ${VOLUME_PATH}/wp_vol:${WP_PATH}
    # Environment variables
    env_file:
      - .env
    # Configuration settings
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    # Guarantee the sequence
    depends_on:
      - wordpress
    ports:
      - "443:443"
    # Keep the service active
    restart: "always"

# Network bridge for orchestrated containers
networks:
  ft_bridge:
    name: ft_bridge
    driver: bridge

# Configuration files
configs:
  mariadb_config:
    file: ./requirements/mariadb/conf/my.cnf
  wordpress_fpm_config:
    file: ./requirements/wordpress/conf/www.conf
  nginx_config:
    file: ./requirements/nginx/conf/nginx.conf
