# Latest version (23.02.19)
version: "3.8"

# Containers orchestrated by Docker Compose
services:
  # MariaDB
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: ft_mariadb
    init: true
    networks:
      - ft_bridge
    volumes:
      - db_vol:/var/lib/mysql
    env_file:
      - .env
    restart: "always"

# Network bridge for orchestrated containers
networks:
  ft_bridge:
    name: ft_bridge
    driver: bridge

# Volumes mounted from host directory for serviced containers
volumes:
  db_vol:
    name: db_vol
    driver: local
    driver_opts:
      # Volume Binding
      device: ${VOLUME_PATH}/mariadb
      o: bind
      type: volume
